version: '3'

volumes:
  mysql_volume:
    driver: 'local'

services:
  db:
    container_name: laravel_mysql
    image:
      mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      TZ: Asia/Tokyo
    volumes:
      - mysql_volume:/var/lib/mysql

  web:
    container_name: laravel_web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - "./htdocs:/var/www/html"

  phpmyadmin:
    container_name: laravel_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8089:80"
